# Use a Miniconda base image
FROM continuumio/miniconda3

# Set environment variables
ENV CONDA_DIR=/opt/conda
ENV PATH=/opt/conda/envs/mdmcleaner/bin:$PATH

# Install system dependencies, including the 'patch' utility
RUN apt-get update && apt-get install -y patch && \
    rm -rf /var/lib/apt/lists/*

# Create and set the working directory
WORKDIR /app

# Install MDMcleaner using Conda into a dedicated environment
# This ensures dependencies are managed cleanly.
RUN conda create -n mdmcleaner -c bioconda -c conda-forge python=3.11 mdmcleaner=0.8.7 --yes && \
    conda clean -afy

# Activate the Conda environment for subsequent RUN, CMD, and ENTRYPOINT instructions
SHELL ["conda", "run", "-n", "mdmcleaner", "/bin/bash", "-c"]

# Patch
COPY MDMcleaner_v0.8.7.patch .
RUN P=$PWD && \
  D=$(find "$CONDA_DIR" -name "mdmcleaner.py" | xargs readlink -f | xargs dirname) && \
  cd $D/ && \
  patch -N < $P/MDMcleaner_v0.8.7.patch && \
  rm $P/MDMcleaner_v0.8.7.patch

# Verify the installation by checking the version
RUN mdmcleaner --help

# Set the default command to show MaxBin2 help
CMD ["mdmcleaner", "--help"]

